name: "Replace Tag"
on:
  push:
    tags: ["stg"]

jobs:
  replace-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.18.1"

      - name: Get node version
        run: node -v

